version: "3.7"

services:
  db:
    build: .docker/postgres
    container_name: db
    restart: always                               
    tty: true                                      
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_ginasio
 
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8000:80"
    depends_on:
      - db