import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import Layout from "@/components/layout";
import AuthContext from "@/contexts/authContext";
import { Inter, Roboto_Mono } from "next/font/google";
import Renderizador from "@/components/SideNav/renderizador";
import LinkContext from "@/contexts/linkNext";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <head>
        {/* script bootstrap  */}
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
          defer
        />
      </head>
      <body className={`${inter.variable} ${roboto_mono.variable}`}>
        <AuthContext>
          <Layout>
            <Header />
            <LinkContext>{children}</LinkContext>
            <Renderizador />
            <Footer />
          </Layout>
        </AuthContext>
      </body>
    </html>
  );
}
